package ja.portfolio.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

@Entity
@Data
public class Project {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Schema(description = "Project ID. Autogenerated in POST requests")
	private Long id;

	@NotBlank(message = "The project title cannot be blank")
	private String title;

	private String description;
	@Column(name = "image_name")
	private String imageName;

	private String githubUrl;
	private String liveDemoUrl;
	@Size(min = 1, message = "Should be min 1 technology per project")
	private String[] technologies; // Para almecenar tecnologías usadas

}
